
use phf::phf_map;
use std::fmt;

pub struct Element {
	pub name: &'static str,
	pub symbol: &'static str,
	pub z: u32,
	pub mass: f64, // amu
	pub radius: Option<f64> // Angstrom
}

impl fmt::Display for Element {
	fn fmt(&self, f: &mut fmt::Formatter) -> fmt::Result {
		write!(f, "{} ({})
Z = {}
Mass = {}
Radius = {:?} Angstrom
", self.name, self.symbol, self.z, self.mass, self.radius)
	}
}



	pub const ELEMENTS: phf::Map<&'static str, Element> = phf_map! {
	"H" => Element{ name: "Hydrogen", symbol: "H", z: 1, mass: 1.007, radius: Some(0.79) },
	"He" => Element{ name: "Helium", symbol: "He", z: 2, mass: 4.002, radius: Some(0.49) },
	"Li" => Element{ name: "Lithium", symbol: "Li", z: 3, mass: 6.941, radius: Some(2.1) },
	"Be" => Element{ name: "Beryllium", symbol: "Be", z: 4, mass: 9.012, radius: Some(1.4) },
	"B" => Element{ name: "Boron", symbol: "B", z: 5, mass: 10.811, radius: Some(1.2) },
	"C" => Element{ name: "Carbon", symbol: "C", z: 6, mass: 12.011, radius: Some(0.91) },
	"N" => Element{ name: "Nitrogen", symbol: "N", z: 7, mass: 14.007, radius: Some(0.75) },
	"O" => Element{ name: "Oxygen", symbol: "O", z: 8, mass: 15.999, radius: Some(0.65) },
	"F" => Element{ name: "Fluorine", symbol: "F", z: 9, mass: 18.998, radius: Some(0.57) },
	"Ne" => Element{ name: "Neon", symbol: "Ne", z: 10, mass: 20.18, radius: Some(0.51) },
	"Na" => Element{ name: "Sodium", symbol: "Na", z: 11, mass: 22.99, radius: Some(2.2) },
	"Mg" => Element{ name: "Magnesium", symbol: "Mg", z: 12, mass: 24.305, radius: Some(1.7) },
	"Al" => Element{ name: "Aluminum", symbol: "Al", z: 13, mass: 26.982, radius: Some(1.8) },
	"Si" => Element{ name: "Silicon", symbol: "Si", z: 14, mass: 28.086, radius: Some(1.5) },
	"P" => Element{ name: "Phosphorus", symbol: "P", z: 15, mass: 30.974, radius: Some(1.2) },
	"S" => Element{ name: "Sulfur", symbol: "S", z: 16, mass: 32.065, radius: Some(1.1) },
	"Cl" => Element{ name: "Chlorine", symbol: "Cl", z: 17, mass: 35.453, radius: Some(0.97) },
	"Ar" => Element{ name: "Argon", symbol: "Ar", z: 18, mass: 39.948, radius: Some(0.88) },
	"K" => Element{ name: "Potassium", symbol: "K", z: 19, mass: 39.098, radius: Some(2.8) },
	"Ca" => Element{ name: "Calcium", symbol: "Ca", z: 20, mass: 40.078, radius: Some(2.2) },
	"Sc" => Element{ name: "Scandium", symbol: "Sc", z: 21, mass: 44.956, radius: Some(2.1) },
	"Ti" => Element{ name: "Titanium", symbol: "Ti", z: 22, mass: 47.867, radius: Some(2.0) },
	"V" => Element{ name: "Vanadium", symbol: "V", z: 23, mass: 50.942, radius: Some(1.9) },
	"Cr" => Element{ name: "Chromium", symbol: "Cr", z: 24, mass: 51.996, radius: Some(1.9) },
	"Mn" => Element{ name: "Manganese", symbol: "Mn", z: 25, mass: 54.938, radius: Some(1.8) },
	"Fe" => Element{ name: "Iron", symbol: "Fe", z: 26, mass: 55.845, radius: Some(1.7) },
	"Co" => Element{ name: "Cobalt", symbol: "Co", z: 27, mass: 58.933, radius: Some(1.7) },
	"Ni" => Element{ name: "Nickel", symbol: "Ni", z: 28, mass: 58.693, radius: Some(1.6) },
	"Cu" => Element{ name: "Copper", symbol: "Cu", z: 29, mass: 63.546, radius: Some(1.6) },
	"Zn" => Element{ name: "Zinc", symbol: "Zn", z: 30, mass: 65.38, radius: Some(1.5) },
	"Ga" => Element{ name: "Gallium", symbol: "Ga", z: 31, mass: 69.723, radius: Some(1.8) },
	"Ge" => Element{ name: "Germanium", symbol: "Ge", z: 32, mass: 72.64, radius: Some(1.5) },
	"As" => Element{ name: "Arsenic", symbol: "As", z: 33, mass: 74.922, radius: Some(1.3) },
	"Se" => Element{ name: "Selenium", symbol: "Se", z: 34, mass: 78.96, radius: Some(1.2) },
	"Br" => Element{ name: "Bromine", symbol: "Br", z: 35, mass: 79.904, radius: Some(1.1) },
	"Kr" => Element{ name: "Krypton", symbol: "Kr", z: 36, mass: 83.798, radius: Some(1.0) },
	"Rb" => Element{ name: "Rubidium", symbol: "Rb", z: 37, mass: 85.468, radius: Some(3.0) },
	"Sr" => Element{ name: "Strontium", symbol: "Sr", z: 38, mass: 87.62, radius: Some(2.5) },
	"Y" => Element{ name: "Yttrium", symbol: "Y", z: 39, mass: 88.906, radius: Some(2.3) },
	"Zr" => Element{ name: "Zirconium", symbol: "Zr", z: 40, mass: 91.224, radius: Some(2.2) },
	"Nb" => Element{ name: "Niobium", symbol: "Nb", z: 41, mass: 92.906, radius: Some(2.1) },
	"Mo" => Element{ name: "Molybdenum", symbol: "Mo", z: 42, mass: 95.96, radius: Some(2.0) },
	"Tc" => Element{ name: "Technetium", symbol: "Tc", z: 43, mass: 98.0, radius: Some(2.0) },
	"Ru" => Element{ name: "Ruthenium", symbol: "Ru", z: 44, mass: 101.07, radius: Some(1.9) },
	"Rh" => Element{ name: "Rhodium", symbol: "Rh", z: 45, mass: 102.906, radius: Some(1.8) },
	"Pd" => Element{ name: "Palladium", symbol: "Pd", z: 46, mass: 106.42, radius: Some(1.8) },
	"Ag" => Element{ name: "Silver", symbol: "Ag", z: 47, mass: 107.868, radius: Some(1.8) },
	"Cd" => Element{ name: "Cadmium", symbol: "Cd", z: 48, mass: 112.411, radius: Some(1.7) },
	"In" => Element{ name: "Indium", symbol: "In", z: 49, mass: 114.818, radius: Some(2.0) },
	"Sn" => Element{ name: "Tin", symbol: "Sn", z: 50, mass: 118.71, radius: Some(1.7) },
	"Sb" => Element{ name: "Antimony", symbol: "Sb", z: 51, mass: 121.76, radius: Some(1.5) },
	"Te" => Element{ name: "Tellurium", symbol: "Te", z: 52, mass: 127.6, radius: Some(1.4) },
	"I" => Element{ name: "Iodine", symbol: "I", z: 53, mass: 126.904, radius: Some(1.3) },
	"Xe" => Element{ name: "Xenon", symbol: "Xe", z: 54, mass: 131.293, radius: Some(1.2) },
	"Cs" => Element{ name: "Cesium", symbol: "Cs", z: 55, mass: 132.905, radius: Some(3.3) },
	"Ba" => Element{ name: "Barium", symbol: "Ba", z: 56, mass: 137.327, radius: Some(2.8) },
	"La" => Element{ name: "Lanthanum", symbol: "La", z: 57, mass: 138.905, radius: Some(2.7) },
	"Ce" => Element{ name: "Cerium", symbol: "Ce", z: 58, mass: 140.116, radius: Some(2.7) },
	"Pr" => Element{ name: "Praseodymium", symbol: "Pr", z: 59, mass: 140.908, radius: Some(2.7) },
	"Nd" => Element{ name: "Neodymium", symbol: "Nd", z: 60, mass: 144.242, radius: Some(2.6) },
	"Pm" => Element{ name: "Promethium", symbol: "Pm", z: 61, mass: 145.0, radius: Some(2.6) },
	"Sm" => Element{ name: "Samarium", symbol: "Sm", z: 62, mass: 150.36, radius: Some(2.6) },
	"Eu" => Element{ name: "Europium", symbol: "Eu", z: 63, mass: 151.964, radius: Some(2.6) },
	"Gd" => Element{ name: "Gadolinium", symbol: "Gd", z: 64, mass: 157.25, radius: Some(2.5) },
	"Tb" => Element{ name: "Terbium", symbol: "Tb", z: 65, mass: 158.925, radius: Some(2.5) },
	"Dy" => Element{ name: "Dysprosium", symbol: "Dy", z: 66, mass: 162.5, radius: Some(2.5) },
	"Ho" => Element{ name: "Holmium", symbol: "Ho", z: 67, mass: 164.93, radius: Some(2.5) },
	"Er" => Element{ name: "Erbium", symbol: "Er", z: 68, mass: 167.259, radius: Some(2.5) },
	"Tm" => Element{ name: "Thulium", symbol: "Tm", z: 69, mass: 168.934, radius: Some(2.4) },
	"Yb" => Element{ name: "Ytterbium", symbol: "Yb", z: 70, mass: 173.054, radius: Some(2.4) },
	"Lu" => Element{ name: "Lutetium", symbol: "Lu", z: 71, mass: 174.967, radius: Some(2.3) },
	"Hf" => Element{ name: "Hafnium", symbol: "Hf", z: 72, mass: 178.49, radius: Some(2.2) },
	"Ta" => Element{ name: "Tantalum", symbol: "Ta", z: 73, mass: 180.948, radius: Some(2.1) },
	"W" => Element{ name: "Wolfram", symbol: "W", z: 74, mass: 183.84, radius: Some(2.0) },
	"Re" => Element{ name: "Rhenium", symbol: "Re", z: 75, mass: 186.207, radius: Some(2.0) },
	"Os" => Element{ name: "Osmium", symbol: "Os", z: 76, mass: 190.23, radius: Some(1.9) },
	"Ir" => Element{ name: "Iridium", symbol: "Ir", z: 77, mass: 192.217, radius: Some(1.9) },
	"Pt" => Element{ name: "Platinum", symbol: "Pt", z: 78, mass: 195.084, radius: Some(1.8) },
	"Au" => Element{ name: "Gold", symbol: "Au", z: 79, mass: 196.967, radius: Some(1.8) },
	"Hg" => Element{ name: "Mercury", symbol: "Hg", z: 80, mass: 200.59, radius: Some(1.8) },
	"Tl" => Element{ name: "Thallium", symbol: "Tl", z: 81, mass: 204.383, radius: Some(2.1) },
	"Pb" => Element{ name: "Lead", symbol: "Pb", z: 82, mass: 207.2, radius: Some(1.8) },
	"Bi" => Element{ name: "Bismuth", symbol: "Bi", z: 83, mass: 208.98, radius: Some(1.6) },
	"Po" => Element{ name: "Polonium", symbol: "Po", z: 84, mass: 210.0, radius: Some(1.5) },
	"At" => Element{ name: "Astatine", symbol: "At", z: 85, mass: 210.0, radius: Some(1.4) },
	"Rn" => Element{ name: "Radon", symbol: "Rn", z: 86, mass: 222.0, radius: Some(1.3) },
	"Fr" => Element{ name: "Francium", symbol: "Fr", z: 87, mass: 223.0, radius: None },
	"Ra" => Element{ name: "Radium", symbol: "Ra", z: 88, mass: 226.0, radius: None },
	"Ac" => Element{ name: "Actinium", symbol: "Ac", z: 89, mass: 227.0, radius: None },
	"Th" => Element{ name: "Thorium", symbol: "Th", z: 90, mass: 232.038, radius: None },
	"Pa" => Element{ name: "Protactinium", symbol: "Pa", z: 91, mass: 231.036, radius: None },
	"U" => Element{ name: "Uranium", symbol: "U", z: 92, mass: 238.029, radius: None },
	"Np" => Element{ name: "Neptunium", symbol: "Np", z: 93, mass: 237.0, radius: None },
	"Pu" => Element{ name: "Plutonium", symbol: "Pu", z: 94, mass: 244.0, radius: None },
	"Am" => Element{ name: "Americium", symbol: "Am", z: 95, mass: 243.0, radius: None },
	"Cm" => Element{ name: "Curium", symbol: "Cm", z: 96, mass: 247.0, radius: None },
	"Bk" => Element{ name: "Berkelium", symbol: "Bk", z: 97, mass: 247.0, radius: None },
	"Cf" => Element{ name: "Californium", symbol: "Cf", z: 98, mass: 251.0, radius: None },
	"Es" => Element{ name: "Einsteinium", symbol: "Es", z: 99, mass: 252.0, radius: None },
	"Fm" => Element{ name: "Fermium", symbol: "Fm", z: 100, mass: 257.0, radius: None },
	"Md" => Element{ name: "Mendelevium", symbol: "Md", z: 101, mass: 258.0, radius: None },
	"No" => Element{ name: "Nobelium", symbol: "No", z: 102, mass: 259.0, radius: None },
	"Lr" => Element{ name: "Lawrencium", symbol: "Lr", z: 103, mass: 262.0, radius: None },
	"Rf" => Element{ name: "Rutherfordium", symbol: "Rf", z: 104, mass: 261.0, radius: None },
	"Db" => Element{ name: "Dubnium", symbol: "Db", z: 105, mass: 262.0, radius: None },
	"Sg" => Element{ name: "Seaborgium", symbol: "Sg", z: 106, mass: 266.0, radius: None },
	"Bh" => Element{ name: "Bohrium", symbol: "Bh", z: 107, mass: 264.0, radius: None },
	"Hs" => Element{ name: "Hassium", symbol: "Hs", z: 108, mass: 267.0, radius: None },
	"Mt" => Element{ name: "Meitnerium", symbol: "Mt", z: 109, mass: 268.0, radius: None },
	"Ds " => Element{ name: "Darmstadtium ", symbol: "Ds ", z: 110, mass: 271.0, radius: None },
	"Rg " => Element{ name: "Roentgenium ", symbol: "Rg ", z: 111, mass: 272.0, radius: None },
	"Cn " => Element{ name: "Copernicium ", symbol: "Cn ", z: 112, mass: 285.0, radius: None },
	"Nh" => Element{ name: "Nihonium", symbol: "Nh", z: 113, mass: 284.0, radius: None },
	"Fl" => Element{ name: "Flerovium", symbol: "Fl", z: 114, mass: 289.0, radius: None },
	"Mc" => Element{ name: "Moscovium", symbol: "Mc", z: 115, mass: 288.0, radius: None },
	"Lv" => Element{ name: "Livermorium", symbol: "Lv", z: 116, mass: 292.0, radius: None },
	"Ts" => Element{ name: "Tennessine", symbol: "Ts", z: 117, mass: 295.0, radius: None },
	"Og" => Element{ name: "Oganesson", symbol: "Og", z: 118, mass: 294.0, radius: None },

};
